from faker import Faker

print("####### Create fake test data #######")

faker = Faker()
print(f"Name: {faker.name()}")
print(f"Address: {faker.address()}")
print(f"Phone: {faker.phone_number()}")
print(f"E-mail: {faker.email()}")
print(f"URL: {faker.url()}")
print('------------------------------------')
print(f"Country: {faker.country()}")
print(f"Latitude: {faker.latitude()}")
print(f"Longitude: {faker.longitude()}")
print('------------------------------------')
print(f"SSN: {faker.ssn()}")
print(f"Job: {faker.job()}")
print(f"Text: {faker.text()}")
print(f"A color: {faker.color()}")
print(f"Emoji: {faker.emoji()}")
print('------------------------------------')
print(f'A word: {faker.word()}')
print(f'Six words: {faker.words(6)}')
print('------------------------------------')
print(f'Simple profile: {faker.simple_profile()}')
print('------------------------------------')
print(f'md5: {faker.md5()}')
print(f'sha1: {faker.sha1()}')
print(f'sha256: {faker.sha256()}')
print(f'uuid4: {faker.uuid4()}')
print('------------------------------------')
print(f'Email: {faker.email()}')
print(f'Safe email: {faker.safe_email()}')
print(f'Free email: {faker.free_email()}')
print(f'Company email: {faker.company_email()}')
print('------------------------------------')
print(f'Host name: {faker.hostname()}')
print(f'Domain name: {faker.domain_name()}')
print(f'Domain word: {faker.domain_word()}')
print(f'TLD: {faker.tld()}')
print('------------------------------------')
print(f'IPv4: {faker.ipv4()}')
print(f'IPv6: {faker.ipv6()}')
print(f'MAC address: {faker.mac_address()}')
print('------------------------------------')
print(f'Slug: {faker.slug()}')
print(f'Image URL: {faker.image_url()}')
print('------------------------------------')
print(f'Date of birth: {faker.date_of_birth()}')
print(f'Century: {faker.century()}')
print(f'Year: {faker.year()}')
print(f'Month: {faker.month()}')
print(f'Month name: {faker.month_name()}')
print(f'Day of week: {faker.day_of_week()}')
print(f'Day of month: {faker.day_of_month()}')
print(f'Time zone: {faker.timezone()}')
print(f'AM/PM: {faker.am_pm()}')
print('------------------------------------')
print(f'currency: {faker.currency()}')
print(f'currency name: {faker.currency_name()}')
print(f'currency code: {faker.currency_code()}')
print('------------------------------------')
print(f'Datetime this century: {faker.date_time_this_century()}')
print(f'Datetime this decade: {faker.date_time_this_decade()}')
print(f'Datetime this year: {faker.date_time_this_year()}')
print(f'Datetime this month: {faker.date_time_this_month()}')
print('------------------------------------')
print(f'Date this century: {faker.date_this_century()}')
print(f'Date this decade: {faker.date_this_decade()}')
print(f'Date this year: {faker.date_this_year()}')
print(f'Date this month: {faker.date_this_month()}')
print('------------------------------------')
print(f'Unix time: {faker.unix_time()}')
print(f'Datetime: {faker.date_time()}')
print(f'iso8601: {faker.iso8601()}')
print(f'Date: {faker.date()}')
print(f'Time: {faker.time()}')
print('------------------------------------')
print(f"Datetime between -7d and now: {faker.date_time_between(start_date='-7d', end_date='now')}")
print(f"Datetime between -15y and now: {faker.date_time_between(start_date='-15d', end_date='now')}")
print(f"Date between: {faker.date_between()}")
print('------------------------------------')
print(f"Future datetime: {faker.future_datetime()}")
print(f"Future date: {faker.future_date()}")
print(f"Past datetime: {faker.past_datetime()}")
print(f"Past date: {faker.past_date()}")
print('------------------------------------')
